name: Terraform Workflow

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Configure Terraform CLI
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply
      env:
        TF_VAR_subscription_id: ${{ secrets.subscription_id }}
        TF_VAR_client_id: ${{ secrets.client_id }}
        TF_VAR_client_secret: ${{ secrets.client_secret }}
        TF_VAR_tenant_id: ${{ secrets.tenant_id }}

