
  name: Terraform Test

  on:
    push: 
    workflow_dispatch:
    
  jobs:
    build:

      runs-on: ubuntu_latest

      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2

        - name: Check Terraform Version
          run: which terraform